In [1]:
import torch

In [3]:
x = torch.rand(10)
print(x.size())

torch.Size([10])


In [4]:
temp = torch.FloatTensor([23,24,23,25,26])
temp.size()

torch.Size([5])

In [16]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_tensor = torch.from_numpy(boston.data)
print(boston_tensor.size())
print(boston_tensor[2:6, 5:8])

torch.Size([506, 13])
tensor([[ 7.1850, 61.1000,  4.9671],
        [ 6.9980, 45.8000,  6.0622],
        [ 7.1470, 54.2000,  6.0622],
        [ 6.4300, 58.7000,  6.0622]], dtype=torch.float64)


### Tensors on GPU

In [23]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a + b
print(c)
d = torch.add(a,b)
print(d)
print(a.add_(5))
print('a*b', a*b)
print('a.mul', a.mul(b))
print('a.mul_', a.mul_(b))

tensor([[1.0174, 1.7475],
        [0.6723, 0.8184]])
tensor([[1.0174, 1.7475],
        [0.6723, 0.8184]])
tensor([[5.5685, 5.8146],
        [5.1644, 5.0859]])
a*b tensor([[2.5001, 5.4249],
        [2.6228, 3.7259]])
a.mul tensor([[2.5001, 5.4249],
        [2.6228, 3.7259]])
a.mul_ tensor([[2.5001, 5.4249],
        [2.6228, 3.7259]])


In [24]:
import time
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)
t0 = time.time()
a.matmul(b)
print('time taken:', time.time()-t0)
a = a.cuda()
b = b.cuda()
t0 = time.time()
a.matmul(b)
print('time taken:', time.time()-t0)


time taken: 8.677043199539185


RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:51